# Valores predeterminados del chart
replicaCount: 3

image:
  repository: manualonsoj/practica
  tag: kubernetes
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30001

redis:
  host: redis
  port: 6379

secret:
  REDIS_PASSWORD: "a2VlcGNvZGluZw=="

configmap:
  REDIS_HOST: redis
  REDIS_PORT: "6379"

